
attr = ['API', 'CollideEvent', 'DamagedEvent', 'DiedEvent', 'HasResult', 'InitEvent', 'InteractEvent', 'KilledEntityEvent',
     'MeleeAttackEvent', 'RangedLaunchedEvent', 'Result', 'TargetEvent', 'TargetLostEvent', 'TimerEvent', 'UpdateEvent',
     '__class__', '__copy__', '__deepcopy__', '__delattr__', '__doc__', '__ensure_finalizer__', '__eq__', '__format__',
     '__getattribute__', '__hash__', '__init__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__',
     '__setattr__', '__str__', '__subclasshook__', '__unicode__', 'cancelable', 'canceled', 'class', 'equals',
     'getClass', 'getListenerList', 'getPhase', 'getResult', 'hasResult', 'hashCode', 'isCancelable', 'isCanceled',
     'listenerList', 'notify', 'notifyAll', 'npc', 'phase', 'result', 'setCanceled', 'setPhase', 'setResult',
     'toString', 'wait']


npc_attr = ['MCEntity', 'UUID', '__class__', '__copy__', '__deepcopy__', '__delattr__', '__doc__', '__ensure_finalizer__',
            '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__ne__', '__new__', '__reduce__',
            '__reduce_ex__', '__repr__', '__setattr__', '__str__', '__subclasshook__', '__unicode__', 'addMark',
            'addPotionEffect', 'addRider', 'addTag', 'advanced', 'age', 'ai', 'alive', 'allRiders', 'attackTarget',
            'attacking', 'blockX', 'blockY', 'blockZ', 'burning', 'canSeeEntity', 'child', 'class', 'clearNavigation',
            'clearPotionEffects', 'clearRiders', 'damage', 'despawn', 'display', 'dropItem', 'entityName', 'entityNbt',
            'equals', 'executeCommand', 'extinguish', 'eyeHeight', 'faction', 'generateNewUUID', 'getAdvanced',
            'getAge', 'getAi', 'getAllRiders', 'getArmor', 'getAttackTarget', 'getBlockX', 'getBlockY', 'getBlockZ',
            'getClass', 'getDialog', 'getDisplay', 'getEntityName', 'getEntityNbt', 'getEyeHeight', 'getFaction',
            'getHealth', 'getHeight', 'getHomeX', 'getHomeY', 'getHomeZ', 'getInventory', 'getJob', 'getLastAttacked',
            'getLastAttackedTime', 'getMCEntity', 'getMainhandItem', 'getMarks', 'getMaxHealth', 'getMotionX',
            'getMotionY', 'getMotionZ', 'getMount', 'getMoveForward', 'getMoveStrafing', 'getMoveVertical', 'getName',
            'getNavigationPath', 'getNbt', 'getOffhandItem', 'getOffsetX', 'getOffsetY', 'getOffsetZ', 'getOwner',
            'getPitch', 'getPos', 'getPotionEffect', 'getRiders', 'getRole', 'getRotation', 'getStats',
            'getStoreddata', 'getTags', 'getTempdata', 'getTimers', 'getType', 'getTypeName', 'getUUID', 'getWidth',
            'getWorld', 'getX', 'getY', 'getZ', 'giveItem', 'hasCustomName', 'hasTag', 'hashCode', 'health',
            'height', 'homeX', 'homeY', 'homeZ', 'inFire', 'inLava', 'inWater', 'inventory', 'isAlive', 'isAttacking',
            'isBurning', 'isChild', 'isNavigating', 'isSneaking', 'isSprinting', 'job', 'jump', 'kill', 'knockback',
            'lastAttacked', 'lastAttackedTime', 'mainhandItem', 'marks', 'maxHealth', 'motionX', 'motionY', 'motionZ',
            'mount', 'moveForward', 'moveStrafing', 'moveVertical', 'name', 'navigateTo', 'navigating',
            'navigationPath', 'nbt', 'notify', 'notifyAll', 'offhandItem', 'offsetX', 'offsetY', 'offsetZ', 'owner',
            'pitch', 'playAnimation', 'pos', 'rayTraceBlock', 'rayTraceEntities', 'removeMark', 'removeTag', 'reset',
            'riders', 'role', 'rotation', 'say', 'sayTo', 'setArmor', 'setAttackTarget', 'setBurning', 'setDialog',
            'setEntityNbt', 'setFaction', 'setHealth', 'setHome', 'setMainhandItem', 'setMaxHealth', 'setMotionX',
            'setMotionY', 'setMotionZ', 'setMount', 'setMoveForward', 'setMoveStrafing', 'setMoveVertical', 'setName',
            'setOffhandItem', 'setOffset', 'setPitch', 'setPos', 'setPosition', 'setRotation', 'setX', 'setY', 'setZ',
            'shootItem', 'sneaking', 'spawn', 'sprinting', 'stats', 'storeAsClone', 'storeddata', 'swingMainhand',
            'swingOffhand', 'tags', 'tempdata', 'timers', 'toString', 'type', 'typeName', 'typeOf', 'updateClient',
            'wait', 'width', 'world', 'x', 'y', 'z']

Timers_attr = ['__class__', '__copy__', '__deepcopy__', '__delattr__', '__doc__', '__ensure_finalizer__', '__eq__',
               '__format__', '__getattribute__', '__hash__', '__init__', '__ne__', '__new__', '__reduce__',
               '__reduce_ex__', '__repr__', '__setattr__', '__str__', '__subclasshook__', '__unicode__', 'class',
               'clear', 'equals', 'forceStart', 'getClass', 'has', 'hashCode', 'notify', 'notifyAll', 'readFromNBT',
               'reset', 'start', 'stop', 'toString', 'update', 'wait', 'writeToNBT']
